//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTrips.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusTripsDbEntities : DbContext
    {
        public BusTripsDbEntities()
            : base("name=BusTripsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<Bus> Bus { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<DepartureCity> DepartureCity { get; set; }
        public virtual DbSet<DestinationCity> DestinationCity { get; set; }
        public virtual DbSet<Model> Model { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
